project:
  type: book
  output-dir: docs

book:
  title: "The Remarkable Diary of Thomas Russell while at Skidegate Inlet, Queen Charlotte islands (Haida Gwaii)  September 1870 â€“ May 1871."
  author:
    - name: "Quentin Goodbody"
      affiliation: "Ladysmith Historical Society"
  date: "2025-12-25"

  description: >
    A transcribed and annotated edition of the diaries of Thomas Russell,
    documenting coal mining operations, labour, and colonial enterprise
    in the Queen Charlotte Islands during the late nineteenth century.

  cover-image: img/logo.jpg

  site-url: "https://ladysmithhistoricalsociety.ca"
  repo-url: "https://github.com/ladysmithhistoricalsociety/thomas-russell-diaries"
  repo-actions: [edit, issue]

  language: en-CA

  page-navigation: true
  chapters:
    - index.qmd

    - part: "**Diaries**"
      chapters:
        - diary_1.qmd
        - diary_2.qmd
        - diary_3.qmd
        - diary_4.qmd
  
    - part: "**Background**"
      chapters:
        - chap_1.qmd
        - chap_2.qmd
        - chap_3.qmd
        - chap_4.qmd
        - maps.qmd
        
    - part: "**Geology**"
      chapters:
        - chap_5.qmd
        - chap_6.qmd
        
    - part: "**Appendices**"
      chapters:
      - thornton.qmd
      - appendix_2.qmd
      - appendix_3.qmd
      - appendix_4.qmd
      - appendix_5.qmd
      - appendix_6.qmd
      - appendix_7.qmd
      - appendix_8.qmd

website: 
  favicon: img/logo.jpg

site-url: https://www.ladysmithhistoricalsociety.ca/

number-depth: 2

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    toc-depth: 4
    link-external-newwindow: true
  
crossref:
  fig-title: "Image"
  
editor: source

